micronaut:
  application:
    name: demo
  executors:
    io:
      type: fixed
      n-threads: 75
  server:
    thread-selection: IO
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

datasources:
  default:
    url: "jdbc:oracle:thin:@${DB_NAME}"
    driverClassName: oracle.jdbc.OracleDriver
    databaseName: "${DB_SCHEMA}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    dialect: ORACLE
    data-source-properties:
      oracle:
        jdbc:
          fanEnabled: false
flyway:
  datasources:
    default:
      enabled: true

owners:
  fred:
    name: Fred
    age: 35
    pets:
      - Dino
      - Baby Puss
  barney:
    name: Barney
    age: 30
    pets:
      - Hoppy